<a href="https://colab.research.google.com/github/z0919648-a11y/PYTHON-PROJECT-/blob/main/copy_of_untitled15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

data = {
    "year":[1912,1912,1920],
    "type":["summer","summer","summer"],
    "decipline":["tennins","tennins","tennins"],
    "even":["singles","doubles","singles"]
}

df = pd.DataFrame(data)
df.to_csv("olympics.csv", index=False)

print("olympics.csv created successfully!")
df.head()

olympics.csv created successfully!

   year    type decipline     even
0  1912  summer   tennins  singles
1  1912  summer   tennins  doubles
2  1920  summer   tennins  singles

In [ ]:
import pandas as pd

data = {
    "name":["Ali","Ahmed","Asia","izza","noor","zainab"],
    "marks":[85,93,90,74,93,90],
}
df = pd.DataFrame(data)
df.to_parquet("result.parquet",index=False)

pd.read_parquet("result.parquet")
print("result.parquet created successfully!")
df.head()

result.parquet created successfully!

    name  marks
0    Ali     85
1  Ahmed     93
2   Asia     90
3   izza     74
4   noor     93

In [ ]:
import pandas as pd

coffee = pd.read_csv("coffee.csv")
coffee.head()

   Day Coffee Type  Price
0  Mon       Latte    350
1  Tue    Espresso    300
2  Wed  Cappuccino    400
3  Thu   Americano    320
4  Fri       Mocha    450

In [ ]:
import pandas as pd

coffee = pd.read_csv("coffee.csv")
coffee.head()

   Day Coffee Type  Price
0  Mon       Latte    350
1  Tue    Espresso    300
2  Wed  Cappuccino    400
3  Thu   Americano    320
4  Fri       Mocha    450

In [ ]:
import pandas as pd

data = {
    "Day": ["Mon", "Tue", "Wed", "Thu", "Fri"],
    "Coffee Type": ["Latte", "Espresso", "Cappuccino", "Americano", "Mocha"],
    "Price": [350, 300, 400, 320, 450]
}

coffee = pd.DataFrame(data)

coffee.to_csv("coffee.csv", index=False)

print("coffee.csv created successfully!")
coffee.head()

coffee.csv created successfully!

   Day Coffee Type  Price
0  Mon       Latte    350
1  Tue    Espresso    300
2  Wed  Cappuccino    400
3  Thu   Americano    320
4  Fri       Mocha    450

In [ ]:
import pandas as pd
data = {
"name" : ["ALi","Ahmed","Asia","izza","noor","zainab"],
"Roll num": [1,2,3,4,5,6],
"subject" : ["English","math","urdu","science","PK studies","math2"],
"Grade":["A","B","C","D","E","F"]
}
student_df = pd.DataFrame(data)

student_df.to_csv("student_data.csv", index=False)

print("student data.csv created successfully!")

student_df.head()

student data.csv created successfully!

    name  Roll num     subject Grade
0    ALi         1     English     A
1  Ahmed         2        math     B
2   Asia         3        urdu     C
3   izza         4     science     D
4   noor         5  PK studies     E

In [ ]:
df = pd.read_csv("student_data.csv")
df.columns

Index(['name', 'Roll num', 'subject', 'Grade'], dtype='object')

In [ ]:
import pandas as pd

coffee = pd.read_csv("coffee.csv")
coffee.sample(3,random_state=1)

   Day Coffee Type  Price
2  Wed  Cappuccino    400
1  Tue    Espresso    300
4  Fri       Mocha    450

In [ ]:
coffee.loc[3:4]

   Day Coffee Type  Price
3  Thu   Americano    320
4  Fri       Mocha    450

In [ ]:
coffee.loc[5:3,"Day"]

Series([], Name: Day, dtype: object)

In [ ]:
coffee.iloc[0:5,[0,2]]

   Day  Price
0  Mon    350
1  Tue    300
2  Wed    400
3  Thu    320
4  Fri    450

In [ ]:
coffee.loc["Mon":"Tue"]

Empty DataFrame
Columns: [Day, Coffee Type, Price]
Index: []

In [ ]:
coffee

   Day Coffee Type  Price
0  Mon       Latte    350
1  Tue    Espresso    300
2  Wed  Cappuccino    400
3  Thu   Americano    320
4  Fri       Mocha    450

In [ ]:
coffee.iat[3 ,0]

'Thu'

In [ ]:
coffee["Day"]

0    Mon
1    Tue
2    Wed
3    Thu
4    Fri
Name: Day, dtype: object

In [ ]:
import pandas as pd
coffee = pd.read_csv("coffee.csv")
coffee.head()

   Day Coffee Type  Price
0  Mon       Latte    350
1  Tue    Espresso    300
2  Wed  Cappuccino    400
3  Thu   Americano    320
4  Fri       Mocha    450

In [ ]:
coffee["Price"]

0    350
1    300
2    400
3    320
4    450
Name: Price, dtype: int64

In [ ]:
coffee['Coffee Type']

0         Latte
1      Espresso
2    Cappuccino
3     Americano
4         Mocha
Name: Coffee Type, dtype: object

In [ ]:
import pandas as pd

data = {
    "Day": ["Monday","Monday","Tuesday","Tuesday","Wednesday","Wednesday","Thursday","Thursday","Friday","Friday"],
    "Coffee Type": ["Latte","Espresso","Latte","Espresso","Latte","Espresso","Latte","Espresso","Latte","Espresso"],
    "Units Sold": [15,25,20,30,25,35,30,40,35,45],
    "Price": [350,300,350,300,350,300,350,300,350,300],
    "Payment": ["Cash","Card","Cash","Card","Cash","Card","Cash","Card","Cash","Card"]
}

coffee = pd.DataFrame(data)

coffee["Total Sales"] = coffee["Units Sold"] * coffee["Price"]

coffee.to_csv("coffee_sales.csv", index=False)

print(coffee)

         Day Coffee Type  Units Sold  Price Payment  Total Sales
0     Monday       Latte          15    350    Cash         5250
1     Monday    Espresso          25    300    Card         7500
2    Tuesday       Latte          20    350    Cash         7000
3    Tuesday    Espresso          30    300    Card         9000
4  Wednesday       Latte          25    350    Cash         8750
5  Wednesday    Espresso          35    300    Card        10500
6   Thursday       Latte          30    350    Cash        10500
7   Thursday    Espresso          40    300    Card        12000
8     Friday       Latte          35    350    Cash        12250
9     Friday    Espresso          45    300    Card        13500

In [ ]:
coffee.sort_values(by=["Units Sold", "Coffee Type"], ascending=False)

         Day Coffee Type  Units Sold  Price Payment  Total Sales
9     Friday    Espresso          45    300    Card        13500
7   Thursday    Espresso          40    300    Card        12000
8     Friday       Latte          35    350    Cash        12250
5  Wednesday    Espresso          35    300    Card        10500
6   Thursday       Latte          30    350    Cash        10500
3    Tuesday    Espresso          30    300    Card         9000
4  Wednesday       Latte          25    350    Cash         8750
1     Monday    Espresso          25    300    Card         7500
2    Tuesday       Latte          20    350    Cash         7000
0     Monday       Latte          15    350    Cash         5250

In [ ]:
coffee.sort_values(by=["Units Sold", "Coffee Type"], ascending=(0,1))

         Day Coffee Type  Units Sold  Price Payment  Total Sales
9     Friday    Espresso          45    300    Card        13500
7   Thursday    Espresso          40    300    Card        12000
5  Wednesday    Espresso          35    300    Card        10500
8     Friday       Latte          35    350    Cash        12250
3    Tuesday    Espresso          30    300    Card         9000
6   Thursday       Latte          30    350    Cash        10500
1     Monday    Espresso          25    300    Card         7500
4  Wednesday       Latte          25    350    Cash         8750
2    Tuesday       Latte          20    350    Cash         7000
0     Monday       Latte          15    350    Cash         5250

In [ ]:
for index,row in coffee.iterrows():
  print(index)
  print(row)
  print("\n\n\n\n\n")

0
Day            Monday
Coffee Type     Latte
Units Sold         15
Price             350
Payment          Cash
Total Sales      5250
Name: 0, dtype: object






1
Day              Monday
Coffee Type    Espresso
Units Sold           25
Price               300
Payment            Card
Total Sales        7500
Name: 1, dtype: object






2
Day            Tuesday
Coffee Type      Latte
Units Sold          20
Price              350
Payment           Cash
Total Sales       7000
Name: 2, dtype: object






3
Day             Tuesday
Coffee Type    Espresso
Units Sold           30
Price               300
Payment            Card
Total Sales        9000
Name: 3, dtype: object






4
Day            Wednesday
Coffee Type        Latte
Units Sold            25
Price                350
Payment             Cash
Total Sales         8750
Name: 4, dtype: object






5
Day            Wednesday
Coffee Type     Espresso
Units Sold            35
Price                300
Payment             Card
Total Sales        10500
Name: 5, dtype: object






6
Day            Thursday
Coffee Type       Latte
Units Sold           30
Price               350
Payment            Cash
Total Sales       10500
Name: 6, dtype: object






7
Day            Thursday
Coffee Type    Espresso
Units Sold           40
Price               300
Payment            Card
Total Sales       12000
Name: 7, dtype: object






8
Day            Friday
Coffee Type     Latte
Units Sold         35
Price             350
Payment          Cash
Total Sales     12250
Name: 8, dtype: object






9
Day              Friday
Coffee Type    Espresso
Units Sold           45
Price               300
Payment            Card
Total Sales       13500
Name: 9, dtype: object